// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.ios:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjK_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z',
    appId: '1:1092110353855:web:1234567890abcdef',
    messagingSenderId: '1092110353855',
    projectId: 'quad-connect-58e7a',
    storageBucket: 'quad-connect-58e7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjK_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z_Z',
    appId: '1:1092110353855:ios:1234567890abcdef',
    messagingSenderId: '1092110353855',
    projectId: 'quad-connect-58e7a',
    databaseURL: 'https://quad-connect-58e7a-default-rtdb.firebaseio.com',
    storageBucket: 'quad-connect-58e7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHDx0eyoyPaSZzWFF9xFwrpthbpuh7ycs',
    appId: '1:1092110353855:android:0a52085be6441e07f80d0a',
    messagingSenderId: '1092110353855',
    projectId: 'quad-connect-58e7a',
    databaseURL: 'https://quad-connect-58e7a-default-rtdb.firebaseio.com',
    storageBucket: 'quad-connect-58e7a.firebasestorage.app',
  );
}
